name: Update README with Random Meme URL

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Random Meme URL
        id: fetch-meme-url
        run: |
          meme_url=$(curl -s "http://192.168.1.51:3000/api/random-meme?g=coding")
          echo "::set-output name=url::$meme_url"

      - name: Update README
        run: |
          # Extract the meme URL from the response
          meme_url="${{ steps.fetch-meme-url.outputs.url }}"
          
          # Update the README with the meme URL using the GitHub API
          curl -X PUT "https://api.github.com/repos/nikrp/nikrp/contents/README.md" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -d '{
              "message": "Update README with a random meme URL",
              "content": "'"$meme_url"'",
              "branch": "main"
            }'
